services:
    api:
        build:
            context: .
            dockerfile: Dockerfile

        image: hillel_support
        container_name: hillel_support_api
        ports:
            - "8000:8000"
        env_file: ".env"
        depends_on:
            - database

    database:
        image: "postgres:17"
        container_name: hillel_support_database
        env_file: ".env"
        ports:
            - "5432:5432"
