# Generated by Django 4.2.16 on 2025-03-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("issues", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="issue",
            name="body",
            field=models.TextField(null=True),
        ),
    ]
